# Generated by Django 3.1.3 on 2020-12-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='48px * 48px 크기의 png/jpg 파일을 업로드 해주세요.', upload_to='accounts/avatar/%Y/%m/%d'),
        ),
    ]
